### ISSUE TITLE
Add ability to search all tools (or more of them)

### ISSUE THREAD

**Issue by MusikAnimal** [n3rsti/toolforge-gallery#8]
Thanks for creating this! I love the UI, but it would seem the search only searches the 12 tools that are listed. Toolforge/VPS hosts hundreds of other useful tools, and some really popular ones like XTools and Quarry are missing from the gallery. One might argue the gallery gives undue weight to these hand-picked selections. Better I think would be to randomize the gallery to help users explore new tools. Making screenshots for all those tools is of course very tedious, but I think it would be okay if there is no imagery, or perhaps provide a way for users to submit tools to the gallery along with screenshots and tags. Just a thought!

**Comment by srish** [comment]
@MusikAnimal Sorry it took long for us to reply to your comment. The idea behind this gallery was only to showcase 10-12 manually curated tools to show a wide range of programming languages used to develop them and audiences they serve to inspire new contributors. I think that was not highlighted clearly on the gallery page previously. We have made this change recently. Also, with that intent, then the search button didn't make much sense, so I've disabled that as well. What you are proposing, I believe, should be in the scope of the Toolforge catalog here: https://phabricator.wikimedia.org/T115650. If you have any further suggestions related to improving the gallery, feel free to file an issue here https://github.com/toolforge/tools-gallery. Thanks :)
