### ISSUE TITLE
Clarify selection of tools in the gallery

### ISSUE THREAD

**Issue by srish** [n3rsti/toolforge-gallery#9]
Summarizing thoughts shared by @quiddity-wp via email:
* Clarify how tools are added in the gallery. Add something like "show a vast range of programming languages used to develop Wikimedia tools to inspire new contributors" as that explains the scope/intent of the gallery. 
* Add a "See also: 2 more complete listings of available tools are linked at https://tools.wmflabs.org/ ".
* Clarify how to nominate a tool for addition.

**Comment by framawiki** [comment]
Should also "have a web interface" be in the scope? Current link on "Gerrit Newcomer Bot" tool points to a wikitech page with technical infos, without any way to interact with it.

**Comment by srish** [comment]
Thanks, @quiddity-wp, and @framawiki, for your feedback and sorry it so long to incorporate them. Necessary changes have been made here https://tools-gallery.toolforge.org/. If you want to raise any further issues, you can do so here: https://github.com/toolforge/tools-gallery.
